### ISSUE TITLE
Make uDdbg pip installable

### ISSUE THREAD

**Issue by domenukk** [iGio90/uDdbg#5]
I'm using uDdbg in a project now to debug very much in the same fashion as in the example.
However for this, I have to clone the repo and add it to pythonpath manually (see [here](https://github.com/fgsect/unicorefuzz/blob/master/setupdebug.sh) ).
It would be great if it were pip installable.

**Comment by flux1on** [comment]
Should be addressed by #10

**Comment by domenukk** [comment]
Indeed, thanks a lot!
